name: Generate Podcast Feed
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py
      - name: Push Repo
        run: |
          git config user.name 'github-actions'
          git config user.email 'gillkiranpreet98@gmail.com'
           # Check for changes
            if [[ $(git status --porcelain) ]]; then
              git add .
              git commit -m "Adding Files"
              git push
            else
              echo "No changes to commit"
            fi
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          
          
        
      
